name:                dprox
version:             0.0.1.0
github:              "bjin/dprox"
license:             BSD3
author:              "Bin Jin"
maintainer:          "bjin@ctrl-d.org"
copyright:           "2019 Bin Jin"

synopsis:            a simple DNS proxy server
category:            DNS

dependencies:
- attoparsec
- base >= 4.7 && < 5
- bytestring
- containers
- dns >= 3.0.4
- iproute
- network
- optparse-applicative
- streaming-commons
- unix
- unordered-containers

flags:
  static:
    description: Enable static build
    manual: true
    default: false

ghc-options:
- -Wall
- -O2
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  dprox:
    main:                Main.hs
    source-dirs:         .
    other-modules:
    - Config
    - DomainRoute
    when:
    - condition: flag(static)
      ghc-options: -optl-static

tests:
  dprox-test:
    main:                Test.hs
    source-dirs:         .
    other-modules:
    - DomainRoute
    dependencies:
    - hspec
