version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          name: Restore Cached Dependencies
          keys:
            - cci-dprox-v2-{{ checksum "stack.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Install executable
          command: stack install
      - run:
          name: Run tests
          command: stack test
      - save_cache:
          name: Cache Dependencies
          key: cci-dprox-v2-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
